/**
 * Phase 4 — Isolated Development Fixtures
 *
 * Benchmark: Restaurant Online Ordering & Smart Table Booking
 * Used for development testing and safe offline fallback.
 * Strictly isolated — never hardcoded into production data flows.
 */

import { PlanningBlueprint, DEFAULT_ASSUMPTIONS } from "./planning-types";

export const RESTAURANT_PLANNING_FIXTURE: PlanningBlueprint = {
  id: "plan_fixture_restaurant_v1",
  projectTitle: "AI-Powered Restaurant Ordering & Smart Table Booking Platform",
  generatedAt: new Date().toISOString(),
  assumptions: {
    ...DEFAULT_ASSUMPTIONS,
    expectedAutomationRatePercent: 70,
    expectedAdoptionRatePercent: 85,
    annualTransactionVolume: 12000,
  },
  confidence: {
    overall: "high",
    requirementsScore: 88,
    technicalScore: 85,
    financialScore: 80,
    notes: [
      "Requirements structured from Phase 1 discovery and Phase 2 process flows",
      "API and database entities defined in technical schema",
      "Estimates derived from 8 screens, 9 APIs, and 4 database entities",
      "All figures represent planning estimation ranges — not guaranteed delivery commitments",
    ],
  },
  workBreakdown: [
    {
      id: "wbs_r_1_1",
      wbsCode: "1.1",
      title: "Restaurant Business Flow & Menu Architecture",
      description: "Define dining room table layout, reservation rules, menu categorization, modifier groups, and order lifecycle states.",
      category: "discovery",
      phase: "Phase 1: Discovery",
      estimatedHours: { low: 12, likely: 16, high: 22 },
      complexity: "medium",
      dependencies: [],
      assignedRole: "Business Analyst",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_1_2",
      wbsCode: "1.2",
      title: "Technical Architecture & API Contract Specification",
      description: "Define real-time table locking mechanism, payment gateway webhook contracts, and kitchen display event schemas.",
      category: "discovery",
      phase: "Phase 1: Discovery",
      estimatedHours: { low: 10, likely: 14, high: 20 },
      complexity: "high",
      dependencies: ["wbs_r_1_1"],
      assignedRole: "Solution Architect",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_2_1",
      wbsCode: "2.1",
      title: "Customer Web & Mobile Ordering Wireframes",
      description: "Design interactive visual wireframes for digital menu, cart, table reservation wizard, checkout, and live order tracker.",
      category: "ux_design",
      phase: "Phase 2: Design",
      estimatedHours: { low: 30, likely: 40, high: 56 },
      complexity: "medium",
      dependencies: ["wbs_r_1_1"],
      assignedRole: "UI/UX Designer",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_2_2",
      wbsCode: "2.2",
      title: "Host Stand & Kitchen Display Dashboard UX",
      description: "Design floorplan management matrix, real-time table status grid, and kitchen order ticket queuing interface.",
      category: "ux_design",
      phase: "Phase 2: Design",
      estimatedHours: { low: 20, likely: 28, high: 38 },
      complexity: "high",
      dependencies: ["wbs_r_2_1"],
      assignedRole: "UI/UX Designer",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_3_1",
      wbsCode: "3.1",
      title: "Customer Ordering & Table Booking Frontend",
      description: "Build Next.js responsive client application with table time-slot picker, cart, multi-step checkout, and live status polling.",
      category: "frontend",
      phase: "Phase 3: Development",
      estimatedHours: { low: 65, likely: 90, high: 125 },
      complexity: "high",
      dependencies: ["wbs_r_2_2"],
      assignedRole: "Frontend Developer",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_3_2",
      wbsCode: "3.2",
      title: "Staff & Kitchen Real-Time Dashboard",
      description: "Build floor manager tablet dashboard with live WebSocket state updates for new incoming orders and table seatings.",
      category: "frontend",
      phase: "Phase 3: Development",
      estimatedHours: { low: 40, likely: 55, high: 75 },
      complexity: "medium",
      dependencies: ["wbs_r_3_1"],
      assignedRole: "Frontend Developer",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_4_1",
      wbsCode: "4.1",
      title: "Core Order & Reservation Backend APIs",
      description: "Build REST endpoints for menu item lookup, atomic table reservation lock, order creation, and status transitions.",
      category: "backend",
      phase: "Phase 3: Development",
      estimatedHours: { low: 50, likely: 70, high: 95 },
      complexity: "high",
      dependencies: ["wbs_r_1_2"],
      assignedRole: "Backend Developer",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_5_1",
      wbsCode: "5.1",
      title: "PostgreSQL Database Schema & Table Inventory Model",
      description: "Implement relational tables for tables, reservations, orders, items, and customers with Row-Level Security.",
      category: "database",
      phase: "Phase 3: Development",
      estimatedHours: { low: 22, likely: 30, high: 42 },
      complexity: "medium",
      dependencies: ["wbs_r_1_2"],
      assignedRole: "Backend Developer",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_6_1",
      wbsCode: "6.1",
      title: "AI Smart Table Seating & Turn-Time Optimizer",
      description: "Integrate Gemini AI model to dynamically predict table turnaround times and recommend optimal seating arrangements.",
      category: "ai_ml",
      phase: "Phase 3: Development",
      estimatedHours: { low: 30, likely: 42, high: 58 },
      complexity: "high",
      dependencies: ["wbs_r_4_1"],
      assignedRole: "AI/ML Engineer",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_6_2",
      wbsCode: "6.2",
      title: "Automated Multi-Channel Notification Engine",
      description: "Configure instant WhatsApp, SMS, and email alerts for reservation confirmation, table readiness, and receipt delivery.",
      category: "integration",
      phase: "Phase 3: Development",
      estimatedHours: { low: 18, likely: 24, high: 34 },
      complexity: "medium",
      dependencies: ["wbs_r_4_1"],
      assignedRole: "Backend Developer",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_8_1",
      wbsCode: "8.1",
      title: "End-to-End Testing & Concurrency Load Validation",
      description: "Simulate peak Friday dinner rush with 50 concurrent reservation requests and validate zero double-booking integrity.",
      category: "testing",
      phase: "Phase 4: Testing",
      estimatedHours: { low: 28, likely: 38, high: 52 },
      complexity: "medium",
      dependencies: ["wbs_r_3_2", "wbs_r_6_1"],
      assignedRole: "QA Engineer",
      status: "todo",
      isAIGenerated: false,
    },
    {
      id: "wbs_r_9_1",
      wbsCode: "9.1",
      title: "Production Cloud Deployment & Staff Onboarding",
      description: "Deploy to serverless edge cluster, configure SSL/DNS, connect payment gateway, and train restaurant floor staff.",
      category: "devops",
      phase: "Phase 5: Deployment",
      estimatedHours: { low: 16, likely: 22, high: 30 },
      complexity: "medium",
      dependencies: ["wbs_r_8_1"],
      assignedRole: "DevOps Engineer",
      status: "todo",
      isAIGenerated: false,
    },
  ],
  resources: [
    {
      id: "res_r_fe",
      role: "Frontend Developer",
      skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "WebSocket"],
      allocationPercent: 100,
      estimatedHours: 145,
      hourlyRate: 1800,
      estimatedCost: 261000,
      durationWeeks: 4,
      responsibilities: ["Build Customer Web App", "Build Host Live Tablet Dashboard", "Implement Responsive Menus"],
      isAssumption: true,
    },
    {
      id: "res_r_be",
      role: "Backend Developer",
      skills: ["Node.js", "PostgreSQL", "REST APIs", "Supabase", "Twilio"],
      allocationPercent: 100,
      estimatedHours: 124,
      hourlyRate: 2200,
      estimatedCost: 272800,
      durationWeeks: 4,
      responsibilities: ["Build Table & Order APIs", "Database Schema & Atomic Locks", "WhatsApp/SMS Integration"],
      isAssumption: true,
    },
    {
      id: "res_r_ai",
      role: "AI/ML Engineer",
      skills: ["Gemini 3.6 Flash", "Prompt Engineering", "Predictive Analytics"],
      allocationPercent: 75,
      estimatedHours: 42,
      hourlyRate: 3200,
      estimatedCost: 134400,
      durationWeeks: 2,
      responsibilities: ["Implement Table Optimization Engine", "No-Show Risk Predictor", "Quality Verification"],
      isAssumption: true,
    },
    {
      id: "res_r_ux",
      role: "UI/UX Designer",
      skills: ["Figma", "Design Systems", "Mobile UI", "Usability Testing"],
      allocationPercent: 80,
      estimatedHours: 68,
      hourlyRate: 1600,
      estimatedCost: 108800,
      durationWeeks: 3,
      responsibilities: ["Customer Reservation Wizard UX", "Floor Manager Tablet Grid UI", "Component Library"],
      isAssumption: true,
    },
    {
      id: "res_r_qa",
      role: "QA Engineer",
      skills: ["Concurrency Testing", "API Automation", "Cross-Device Validation"],
      allocationPercent: 60,
      estimatedHours: 38,
      hourlyRate: 1200,
      estimatedCost: 45600,
      durationWeeks: 2,
      responsibilities: ["Stress Test Friday Rush Concurrency", "End-to-End Booking Flow Validation"],
      isAssumption: true,
    },
    {
      id: "res_r_devops",
      role: "DevOps Engineer",
      skills: ["Vercel Edge", "PostgreSQL Cloud", "Monitoring", "CI/CD"],
      allocationPercent: 50,
      estimatedHours: 22,
      hourlyRate: 2600,
      estimatedCost: 57200,
      durationWeeks: 2,
      responsibilities: ["Provision Production Cluster", "Configure CI/CD Pipelines", "Set up Telemetry & Alarms"],
      isAssumption: true,
    },
    {
      id: "res_r_pm",
      role: "Project Manager / Business Analyst",
      skills: ["Agile/Scrum", "Hospitality Workflows", "Stakeholder Delivery"],
      allocationPercent: 50,
      estimatedHours: 30,
      hourlyRate: 2000,
      estimatedCost: 60000,
      durationWeeks: 6,
      responsibilities: ["Sprint Coordination", "Restaurant Management Sign-off", "Scope & Risk Oversight"],
      isAssumption: true,
    },
  ],
  milestones: [
    {
      id: "ms_r_1",
      name: "🔍 Discovery & Architecture Sign-Off",
      description: "Requirements locked, table state model defined, API schema validated",
      phase: "Phase 1: Discovery",
      durationWeeks: 1,
      offsetWeeks: 0,
      dependencies: [],
      deliverables: ["Functional specification", "Database entity diagram", "API contract"],
      criticalPath: true,
    },
    {
      id: "ms_r_2",
      name: "🎨 UX Design & Wireframe Approval",
      description: "Customer ordering flows, table booking UX, and host dashboard prototypes approved",
      phase: "Phase 2: Design",
      durationWeeks: 2,
      offsetWeeks: 1,
      dependencies: ["ms_r_1"],
      deliverables: ["Figma prototypes", "Interactive wireframes", "Design system tokens"],
      criticalPath: true,
    },
    {
      id: "ms_r_3",
      name: "💻 Core Platform & AI Seating Engine Complete",
      description: "All frontend screens, backend APIs, and Gemini seating models operational",
      phase: "Phase 3: Development",
      durationWeeks: 3,
      offsetWeeks: 3,
      dependencies: ["ms_r_2"],
      deliverables: ["Full-stack web application", "Live API endpoints", "AI seating engine"],
      criticalPath: true,
    },
    {
      id: "ms_r_4",
      name: "🧪 Concurrency Testing & Staff Training Pass",
      description: "Zero double-booking errors validated under 50 simulated concurrent diners",
      phase: "Phase 4: Testing",
      durationWeeks: 1,
      offsetWeeks: 6,
      dependencies: ["ms_r_3"],
      deliverables: ["QA sign-off report", "UAT approval", "Staff user manual"],
      criticalPath: true,
    },
    {
      id: "ms_r_5",
      name: "🚀 Production Go-Live & Launch",
      description: "Live web application accessible to diners, kitchen printers connected, real-time tracking on",
      phase: "Phase 5: Deployment",
      durationWeeks: 1,
      offsetWeeks: 7,
      dependencies: ["ms_r_4"],
      deliverables: ["Production live deployment", "Active monitoring alarms", "Post-launch report"],
      criticalPath: true,
    },
  ],
  costModel: {
    currency: "₹",
    developmentCost: 533800,
    uiUxDesignCost: 108800,
    aiIntegrationCost: 134400,
    infrastructureMonthlyCost: 8500,
    aiApiMonthlyCost: 3500,
    testingCost: 45600,
    deploymentCost: 57200,
    projectManagementCost: 60000,
    contingencyPercent: 15,
    contingencyAmount: 142470,
    totalInitialCost: 1092270,
    recurringMonthlyCost: 12000,
    annualOperatingCost: 144000,
    lines: [
      { category: "Frontend & Backend Development", label: "Full-Stack Application Development", amount: 533800, type: "one_time", isAssumption: true },
      { category: "UI/UX Design", label: "Customer & Host Dashboard Design", amount: 108800, type: "one_time", isAssumption: true },
      { category: "AI Engineering", label: "Gemini Smart Seating Model", amount: 134400, type: "one_time", isAssumption: true },
      { category: "Quality Assurance", label: "Concurrency & Peak Load Testing", amount: 45600, type: "one_time", isAssumption: true },
      { category: "DevOps & Infrastructure", label: "Cloud Deployment & Setup", amount: 57200, type: "one_time", isAssumption: true },
      { category: "Project Management", label: "Hospitality Workflow Delivery", amount: 60000, type: "one_time", isAssumption: true },
      { category: "Contingency Buffer", label: "15% Scope & Risk Contingency", amount: 142470, type: "one_time", isAssumption: true },
      { category: "Cloud Infrastructure", label: "PostgreSQL Cloud + Edge Hosting", amount: 8500, type: "monthly", isAssumption: true },
      { category: "AI Model Usage", label: "Gemini 3.6 Flash Inference Budget", amount: 3500, type: "monthly", isAssumption: true },
    ],
    low: 873816,
    expected: 1092270,
    high: 1419951,
  },
  roiModel: {
    initialInvestment: 1092270,
    currency: "₹",
    assumptions: [
      { key: "annualVolume", label: "Annual Diners / Transactions", value: 12000, unit: "bookings/year", isUserProvided: false, notes: "Estimated annual table reservation and takeaway order volume" },
      { key: "avgManualMins", label: "Manual Minutes Saved per Booking", value: 4, unit: "minutes", isUserProvided: false, notes: "Eliminates phone intake, physical binder check, and paper entry" },
      { key: "automationRate", label: "Expected Online Booking Adoption", value: 70, unit: "%", isUserProvided: false, notes: "70% of reservations migrate to 24/7 self-service" },
      { key: "hourlyStaffCost", label: "Staff Hourly Opportunity Cost", value: 500, unit: "₹/hr", isUserProvided: false, notes: "Allows frontline staff to focus on in-restaurant diner hospitality" },
      { key: "noShowReduction", label: "No-Show Rate Reduction", value: 15, unit: "%", isUserProvided: false, notes: "Automated WhatsApp reminders reduce empty held tables" },
    ],
    scenarios: [
      {
        scenario: "conservative",
        label: "Conservative (50% digital adoption)",
        annualLaborSaving: 200000,
        annualRevenueLift: 180000,
        annualOtherBenefit: 50000,
        annualBenefit: 430000,
        annualOperatingCost: 144000,
        netAnnualBenefit: 286000,
        paybackMonths: 46,
        firstYearROI: 26,
        threeYearROI: 79,
      },
      {
        scenario: "expected",
        label: "Expected (Base Planning Assumptions)",
        annualLaborSaving: 280000,
        annualRevenueLift: 360000,
        annualOtherBenefit: 120000,
        annualBenefit: 760000,
        annualOperatingCost: 144000,
        netAnnualBenefit: 616000,
        paybackMonths: 21,
        firstYearROI: 56,
        threeYearROI: 170,
      },
      {
        scenario: "optimistic",
        label: "Optimistic (High Peak Season Turnaround)",
        annualLaborSaving: 360000,
        annualRevenueLift: 600000,
        annualOtherBenefit: 180000,
        annualBenefit: 1140000,
        annualOperatingCost: 144000,
        netAnnualBenefit: 996000,
        paybackMonths: 13,
        firstYearROI: 91,
        threeYearROI: 274,
      },
    ],
    formulaNotes: [
      "Annual Labor Savings = Annual Bookings × Minutes Saved ÷ 60 × Digital Adoption % × Hourly Staff Value",
      "Annual Revenue Lift = Recovered No-Show Table Turns × Average Dining Check Value",
      "Net Annual Benefit = Total Annual Benefit − Annual Cloud Operating Cost",
      "Payback Period = Initial Investment ÷ (Net Annual Benefit ÷ 12)",
      "Estimated ranges are deterministic planning projections based on stated assumptions.",
    ],
  },
  risks: [
    {
      id: "r_rf_1",
      title: "Internet or Power Interruption at Restaurant Host Stand",
      description: "Offline host tablet could prevent checking in arriving guests during service.",
      category: "operational",
      probability: "medium",
      impact: "high",
      severity: "high",
      mitigation: "Implement progressive web app (PWA) offline sync and cellular 4G/5G backup SIM on tablet.",
      owner: "DevOps Engineer",
    },
    {
      id: "r_rf_2",
      title: "Concurrent Table Double-Booking During Peak Holiday Rush",
      description: "Multiple diners selecting the same table simultaneously at 8:00 PM.",
      category: "technical",
      probability: "low",
      impact: "critical",
      severity: "high",
      mitigation: "Implement PostgreSQL row-level locks with 5-minute atomic reservation holding tickets.",
      owner: "Backend Developer",
    },
    {
      id: "r_rf_3",
      title: "Staff Hesitation in Adopting Digital Kitchen Display",
      description: "Kitchen crew accustomed to physical paper tickets may ignore tablet display.",
      category: "operational",
      probability: "medium",
      impact: "medium",
      severity: "medium",
      mitigation: "Provide hybrid thermal paper printer alongside live digital screen and conduct hands-on shift training.",
      owner: "Project Manager",
    },
  ],
  scenarios: [
    {
      type: "mvp",
      label: "MVP — Core Table Booking Only",
      description: "Diner booking page + Host management tablet. Excludes menu ordering and AI seating optimization.",
      teamSize: "2 Developers",
      durationWeeks: 4,
      featuresIncluded: ["Table reservation wizard", "Host table check-in tablet", "SMS confirmation"],
      featuresExcluded: ["Digital menu ordering", "Kitchen display system", "AI seating optimization"],
      estimatedCost: { low: 393000, expected: 491000, high: 638000 },
      estimatedROI: 28,
      paybackMonths: 30,
      riskLevel: "low",
      recommendation: "Quickest path to replace physical reservation binders within 1 month.",
    },
    {
      type: "standard",
      label: "Standard — Full Ordering & AI Seating",
      description: "Complete solution including mobile ordering, real-time kitchen display, and Gemini seating AI.",
      teamSize: "4–5 People",
      durationWeeks: 7,
      featuresIncluded: ["All planned features", "Digital menu + cart", "AI seating optimizer", "Kitchen display system"],
      featuresExcluded: ["Multi-location enterprise loyalty network"],
      estimatedCost: { low: 873816, expected: 1092270, high: 1419951 },
      estimatedROI: 56,
      paybackMonths: 21,
      riskLevel: "low",
      recommendation: "Recommended comprehensive transformation delivering peak ROI.",
    },
    {
      type: "enterprise",
      label: "Enterprise — Multi-Chain Franchise Network",
      description: "Centralized multi-restaurant inventory, franchise billing, ERP integration, and customized loyalty.",
      teamSize: "7–10 People",
      durationWeeks: 11,
      featuresIncluded: ["All standard features", "Multi-branch franchise dashboard", "POS hardware integration", "Custom loyalty analytics"],
      featuresExcluded: [],
      estimatedCost: { low: 1747000, expected: 1966000, high: 2293000 },
      estimatedROI: 75,
      paybackMonths: 17,
      riskLevel: "medium",
      recommendation: "For multi-unit restaurant groups managing 5+ dining locations.",
    },
  ],
  totalEstimatedHours: { low: 337, likely: 469, high: 650 },
  durationWeeks: 7,
  criticalPath: [
    "🔍 Discovery & Architecture Sign-Off",
    "🎨 UX Design & Wireframe Approval",
    "💻 Core Platform & AI Seating Engine Complete",
    "🧪 Concurrency Testing & Staff Training Pass",
    "🚀 Production Go-Live & Launch",
  ],
  isAIEnhanced: false,
  isAIGeneratedEstimate: true,
};
