/**
 * Phase 2 — Isolated Development Fixtures
 * 
 * Provides standard test fixtures for development and testing.
 * Includes benchmark: Restaurant Table Booking (Current vs Future State)
 * and generic enterprise fallbacks.
 */

import { ProcessFlow } from "./process-intelligence-types";

export const RESTAURANT_CURRENT_STATE_FIXTURE: ProcessFlow = {
  id: "fixture_restaurant_current",
  name: "Restaurant Table Reservation (Current Manual Workflow)",
  description: "Traditional manual reservation flow involving phone calls, paper checkbooks, and high staff friction.",
  state: "current",
  lanes: [
    { id: "lane_customer", name: "Customer", role: "External Client", color: "#3B82F6" },
    { id: "lane_host", name: "Front Desk Host / Staff", role: "Operations Staff", color: "#F59E0B" },
    { id: "lane_manager", name: "Shift Manager", role: "Management", color: "#8B5CF6" },
    { id: "lane_system", name: "Manual Paper Register / Phone", role: "Legacy System", color: "#64748B" },
  ],
  nodes: [
    {
      id: "node_c1",
      type: "start",
      label: "Customer Decides to Book",
      description: "Customer searches for the restaurant number and initiates contact.",
      laneId: "lane_customer",
      x: 80,
      y: 60,
      duration: "1 min",
    },
    {
      id: "node_c2",
      type: "human-task",
      label: "Customer Dials Phone",
      description: "Customer makes a phone call during restaurant operating hours.",
      laneId: "lane_customer",
      x: 280,
      y: 60,
      duration: "3-5 mins",
      isBottleneck: true,
      bottleneckId: "btn_1",
    },
    {
      id: "node_c3",
      type: "human-task",
      label: "Staff Answers & Notes Request",
      description: "Staff member pauses floor duties to answer phone and write party details on notepad.",
      laneId: "lane_host",
      x: 280,
      y: 220,
      duration: "3 mins",
      isBottleneck: true,
      bottleneckId: "btn_2",
    },
    {
      id: "node_c4",
      type: "human-task",
      label: "Physical Inspection of Table Register",
      description: "Staff flips through physical binder to check if 4-top table is free at 7:30 PM.",
      laneId: "lane_system",
      x: 480,
      y: 540,
      duration: "4 mins",
      isBottleneck: true,
      bottleneckId: "btn_3",
    },
    {
      id: "node_c5",
      type: "decision",
      label: "Table Available?",
      description: "Evaluate if seating capacity exists for requested timeslot.",
      laneId: "lane_host",
      x: 680,
      y: 220,
      duration: "30 sec",
    },
    {
      id: "node_c6",
      type: "human-task",
      label: "Manager Approval for Large Group",
      description: "Staff walks across restaurant to get verbal sign-off from shift manager.",
      laneId: "lane_manager",
      x: 680,
      y: 380,
      duration: "6 mins",
      isBottleneck: true,
      bottleneckId: "btn_4",
    },
    {
      id: "node_c7",
      type: "human-task",
      label: "Manual Entry into Book",
      description: "Pencil in customer name and phone number into paper diary.",
      laneId: "lane_system",
      x: 880,
      y: 540,
      duration: "2 mins",
      isBottleneck: true,
      bottleneckId: "btn_5",
    },
    {
      id: "node_c8",
      type: "human-task",
      label: "Verbal Confirmation on Call",
      description: "Staff returns to handset and tells customer their table is held.",
      laneId: "lane_host",
      x: 880,
      y: 220,
      duration: "1 min",
    },
    {
      id: "node_c9",
      type: "end",
      label: "Manual Reservation Complete",
      description: "Booking locked in physical book. No digital confirmation or reminder sent.",
      laneId: "lane_customer",
      x: 1080,
      y: 60,
      duration: "Instant",
    },
  ],
  edges: [
    { id: "e1", source: "node_c1", target: "node_c2" },
    { id: "e2", source: "node_c2", target: "node_c3", label: "Phone Ringing" },
    { id: "e3", source: "node_c3", target: "node_c4", label: "Lookup" },
    { id: "e4", source: "node_c4", target: "node_c5" },
    { id: "e5", source: "node_c5", target: "node_c6", condition: "Party > 5", label: "Large Party" },
    { id: "e6", source: "node_c5", target: "node_c7", condition: "Standard", label: "Available" },
    { id: "e7", source: "node_c6", target: "node_c7", label: "Approved" },
    { id: "e8", source: "node_c7", target: "node_c8", label: "Recorded" },
    { id: "e9", source: "node_c8", target: "node_c9", label: "Confirmed" },
  ],
  bottlenecks: [
    {
      id: "btn_1",
      nodeId: "node_c2",
      title: "Potential Bottleneck: Phone Line Busy & Operating Hours Bound",
      reason: "Customers cannot reserve outside business hours or when phone lines are congested.",
      severity: "high",
      category: "waiting",
      recommendation: "Provide 24/7 web/mobile self-service booking portal.",
      potentialTimeSaved: "100% of customer wait time",
    },
    {
      id: "btn_2",
      nodeId: "node_c3",
      title: "Potential Bottleneck: Staff Distraction & Service Interruption",
      reason: "Waitstaff repeatedly abandon in-restaurant diner service to answer incoming phone inquiries.",
      severity: "high",
      category: "manual_handoff",
      recommendation: "Automate reservation intake with conversational AI agent and online UI.",
      potentialTimeSaved: "3-5 mins per reservation",
    },
    {
      id: "btn_3",
      nodeId: "node_c4",
      title: "Potential Bottleneck: Manual Binder Lookup & Overbooking Risk",
      reason: "Physical binder checks are slow, prone to human error, double-booking, and illegible handwriting.",
      severity: "high",
      category: "duplicate_data",
      recommendation: "Implement real-time SQL database with synchronized table inventory.",
      potentialTimeSaved: "4 mins per lookup",
    },
    {
      id: "btn_4",
      nodeId: "node_c6",
      title: "Potential Bottleneck: Physical Floor Walk for Manager Sign-off",
      reason: "Host must physically locate manager on busy floor to approve group bookings.",
      severity: "medium",
      category: "approval_delay",
      recommendation: "Configure automated capacity rules with instant push notifications for approvals.",
      potentialTimeSaved: "6 mins per large booking",
    },
    {
      id: "btn_5",
      nodeId: "node_c7",
      title: "Potential Bottleneck: Paper Record Lack of Traceability",
      reason: "No automatic reminders leads to 15-20% no-show rates without cancellation notices.",
      severity: "medium",
      category: "system_dependency",
      recommendation: "Sync booking to cloud CRM with automated WhatsApp/SMS confirmation and reminders.",
      potentialTimeSaved: "Instant sync & 80% no-show reduction",
    },
  ],
  automationOpportunities: [
    {
      id: "opp_1",
      nodeId: "node_c3",
      stepName: "Staff Answers Phone",
      opportunity: "AI Voice Agent / Conversational Reservation Bot",
      rationale: "Natural Language processing can handle 90% of routine table bookings 24/7 in multiple languages.",
      potentialBenefit: "Save 15+ hours of staff time per week; zero missed calls.",
      implementationComplexity: "low",
      suggestedToolOrAI: "Gemini Multimodal Voice + Twilio Webhook",
    },
    {
      id: "opp_2",
      nodeId: "node_c4",
      stepName: "Inspection of Table Register",
      opportunity: "Real-Time Cloud Inventory Engine",
      rationale: "Instant algorithmic seating availability calculation based on party size and dining duration.",
      potentialBenefit: "Zero double-bookings; sub-second verification.",
      implementationComplexity: "low",
      suggestedToolOrAI: "PostgreSQL with Row-Level Locking & Realtime Subscriptions",
    },
  ],
  aiOpportunities: [
    {
      id: "ai_1",
      nodeId: "node_c5",
      stepName: "Table Availability Evaluation",
      aiCapability: "Predictive Seating Optimization & No-Show Probability Scoring",
      modelSuggestion: "Gemini 3.6 Flash ML Classifier",
      expectedImpact: "Increase table turnaround by 22% by dynamically predicting table release times.",
      complexity: "medium",
    },
    {
      id: "ai_2",
      nodeId: "node_c8",
      stepName: "Reservation Confirmation",
      aiCapability: "Multilingual Instant WhatsApp / SMS Confirmation with Calendar Invite",
      modelSuggestion: "Automated Messaging Gateway",
      expectedImpact: "Cuts no-show rates from 18% to under 3%.",
      complexity: "low",
    },
  ],
  optimizations: [
    {
      id: "opt_1",
      type: "automate",
      title: "Shift to 24/7 Digital Self-Service",
      description: "Replace phone calls and paper registers with an instant web booking app.",
      impact: "High (Cuts wait time from 10 mins to 30 secs)",
      effort: "low",
    },
    {
      id: "opt_2",
      type: "ai_assist",
      title: "AI Table Assignment & Turn-Time Forecaster",
      description: "AI continuously maximizes floor occupancy and suggests optimal seating arrangements.",
      impact: "+18% Revenue during peak service hours",
      effort: "medium",
    },
  ],
};

export const RESTAURANT_FUTURE_STATE_FIXTURE: ProcessFlow = {
  id: "fixture_restaurant_future",
  name: "Smart AI-Powered Reservation System (Future State)",
  description: "Modern streamlined digital workflow featuring web/mobile booking, real-time availability, instant confirmations, and automated management.",
  state: "future",
  lanes: [
    { id: "lane_customer", name: "Customer", role: "Digital User", color: "#3B82F6" },
    { id: "lane_ai", name: "AI Agent & Web Gateway", role: "Intelligent Layer", color: "#10B981" },
    { id: "lane_system", name: "Real-Time Cloud Database", role: "Core Infrastructure", color: "#64748B" },
    { id: "lane_host", name: "Host Live Dashboard", role: "Front of House", color: "#F59E0B" },
  ],
  nodes: [
    {
      id: "node_f1",
      type: "start",
      label: "Customer Visits Booking Page",
      description: "User selects party size, preferred date, and time slot via web or mobile app.",
      laneId: "lane_customer",
      x: 80,
      y: 60,
      duration: "30 sec",
    },
    {
      id: "node_f2",
      type: "automated-task",
      label: "Real-Time Availability Check",
      description: "System queries live table matrix and filters open 2-top, 4-top, and booth configurations.",
      laneId: "lane_system",
      x: 300,
      y: 380,
      duration: "100 ms",
    },
    {
      id: "node_f3",
      type: "ai-task",
      label: "AI Seating Optimizer & Turn-Time Predictor",
      description: "AI analyzes historical party dining durations and suggests ideal table match with zero gaps.",
      laneId: "lane_ai",
      x: 520,
      y: 220,
      duration: "250 ms",
    },
    {
      id: "node_f4",
      type: "automated-task",
      label: "Instant Database Lock & Reservation Creation",
      description: "Atomic reservation transaction executed in PostgreSQL with instant confirmation code.",
      laneId: "lane_system",
      x: 740,
      y: 380,
      duration: "50 ms",
    },
    {
      id: "node_f5",
      type: "automated-task",
      label: "Multi-Channel Confirmation & Calendar Sync",
      description: "Sends instant WhatsApp, SMS, and email with .ics calendar invite and 1-click cancel button.",
      laneId: "lane_ai",
      x: 960,
      y: 220,
      duration: "Instant",
    },
    {
      id: "node_f6",
      type: "system-task",
      label: "Live Floor Plan & Host Tablet Updated",
      description: "Realtime WebSocket pushes the new booking to the host stand tablet and kitchen prep count.",
      laneId: "lane_host",
      x: 960,
      y: 540,
      duration: "Instant",
    },
    {
      id: "node_f7",
      type: "end",
      label: "Smooth Arrival & Dining Experience",
      description: "Customer arrives, tablet checks them in automatically, table is ready with zero delays.",
      laneId: "lane_customer",
      x: 1180,
      y: 60,
      duration: "Instant",
    },
  ],
  edges: [
    { id: "ef1", source: "node_f1", target: "node_f2", label: "Select Party & Time" },
    { id: "ef2", source: "node_f2", target: "node_f3", label: "Slot Found" },
    { id: "ef3", source: "node_f3", target: "node_f4", label: "Optimal Table Assigned" },
    { id: "ef4", source: "node_f4", target: "node_f5", label: "Dispatched" },
    { id: "ef5", source: "node_f4", target: "node_f6", label: "WebSocket Sync" },
    { id: "ef6", source: "node_f5", target: "node_f7", label: "Ready to Dine" },
  ],
  bottlenecks: [],
  automationOpportunities: [],
  aiOpportunities: [
    {
      id: "ai_f1",
      nodeId: "node_f3",
      stepName: "Seating Optimizer",
      aiCapability: "Dynamic VIP Tagging and Special Request Recognition",
      modelSuggestion: "Gemini 3.6 Flash",
      expectedImpact: "Personalized guest notes and wine recommendations ready upon arrival.",
      complexity: "low",
    },
  ],
  optimizations: [
    {
      id: "opt_f1",
      type: "ai_assist",
      title: "Predictive Pre-Ordering",
      description: "Allow guests to pre-select appetizers and wine to reduce initial kitchen ramp time.",
      impact: "+14% table turns during dinner service",
      effort: "low",
    },
  ],
};
